### ISSUE TITLE
Organise meeting with Terrence and Eddie

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/modulr#42]
## Task
- [ ] Find out what their roles are
     - [ ] consider equity
     - [ ] financials
     - [ ] is this worth your time????
- [x] organise a time and date
- [x] set an agenda
- [x] send meeting notification and agenda to them
